version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: penpal_demo_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  postgres:
    image: postgres:14
    container_name: penpal_demo_db
    environment:
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo
      POSTGRES_DB: demo_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mailhog:
    image: mailhog/mailhog
    container_name: penpal_demo_mail
    ports:
      - "1025:1025" # SMTP server
      - "8025:8025" # Web UI

volumes:
  redis_data:
  postgres_data: 